name: "Fernanda Hansen P. de Moraes"
description: "The Personal Homepage for Fernanda de Moraes"

url: "http://moraesfernanda.github.io/"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
